### ISSUE TITLE
Error: Cannot read properties of null (reading 'guesses')

### ISSUE THREAD

**Issue by EmpAhmadK** [roedoejet/AnyLanguage-Wordle#14]
I'm sorry if this is the wrong place to post this since I'm still trying to learn about GitHub, but I was trying to make my own with a language using Arabic script, and I got this following error in the [workflow](https://github.com/EmpAhmadK/Kejawi/runs/5717983980)
```
FAIL src/App.test.tsx
  ✕ renders game (86 ms)
  ✓ no surprise characters (23 ms)
  ✓ all words are correct length (16 ms)
  ✓ date is valid (1 ms)

  ● renders game

    TypeError: Cannot read properties of null (reading 'guesses')

      41 |       return []
      42 |     }
    > 43 |     const gameWasWon = loaded.guesses
         |                               ^
      44 |       .map((guess) => guess.join(''))
      45 |       .includes(solution)
      46 |     if (gameWasWon) {
```
Could the script I was using be the cause of this problem or what was it exactly?

**Comment by roedoejet** [comment]
Hi @EmpAhmadK - thanks for posting! Yes, this is a good place to post with issues like this :)

I had a look and saw that you got it working - it looks like the game wasn't rendering because the date was in the future, is that true? I am curious if you will run into other problems using a right-to-left writing system. If you do, I would be grateful if you posted your solutions here so that we can make the game more accessible. Take care.

**Comment by EmpAhmadK** [comment]
Sorry for the late response, I took a break from the project and forgot to check back over here 😅
Yes! That was indeed the problem, sorry I forgot to update over here. Thanks a bunch!

**Comment by roedoejet** [comment]
no worries, thanks for checking back!
